### ISSUE TITLE
Can not build project from console

### ISSUE THREAD

**Issue by vbauer** [nisrulz/recyclerviewhelper#1]
I've got the following error during `gradlew build`:
```
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
```

It looks like gradle wrapper jar file was missed in "gradle/wrapper".

**Comment by nisrulz** [comment]
@vbauer yes, i see the issue. I will update the repository with missing jar files.

**Comment by nisrulz** [comment]
fixed.

**Comment by vbauer** [comment]
Thank you.
