### ISSUE TITLE
Cannot get property 'GROUP' on extra properties extension as it does not exist

### ISSUE THREAD

**Issue by pranaypatel512** [nisrulz/recyclerviewhelper#5]
Thanks for library.

While cloning repository and sync project, I am getting below gradle sync failed message [here](https://github.com/nisrulz/recyclerviewhelper/blob/master/recyclerviewhelper/build.gradle#L38):

`Cannot get property 'GROUP' on extra properties extension as it does not exist`

**Comment by nisrulz** [comment]
Comment the bintray publish block and then rebuild your project

https://github.com/nisrulz/recyclerviewhelper/blob/master/recyclerviewhelper/build.gradle#L30-L62

**Comment by pranaypatel512** [comment]
Build succeed. Thanks for quick replay.
